# Generated by Django 3.0.1 on 2019-12-31 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcela', models.PositiveIntegerField()),
                ('desconto', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cotacao_texto', models.TextField()),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoTexto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cotacao_texto', models.TextField()),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
