# Generated by Django 3.0.2 on 2020-01-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inicial', models.DecimalField(decimal_places=2, max_digits=5)),
                ('valor_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('parcela', models.PositiveIntegerField()),
                ('entrada', models.BooleanField()),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoSvg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('cotacao_texto', models.TextField()),
                ('data_inicial', models.DateField()),
                ('data_final', models.DateField()),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='ConfiguracaoTexto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('cotacao_texto', models.TextField()),
                ('data_inicial', models.DateField(unique=True)),
                ('data_final', models.DateField()),
                ('desconto', models.PositiveIntegerField()),
                ('check_in', models.BooleanField(default=False)),
                ('check_out', models.BooleanField(default=False)),
                ('num_dias', models.BooleanField(default=False)),
                ('num_criancas', models.BooleanField(default=False)),
                ('idade_crianca', models.BooleanField(default=False)),
                ('num_pessoas', models.BooleanField(default=False)),
                ('valor_total', models.BooleanField(default=False)),
                ('valor_real', models.BooleanField(default=False)),
                ('valor_desconto', models.BooleanField(default=False)),
                ('valor_da_parcelas', models.BooleanField(default=False)),
                ('valor_da_parcelas_menos_etrada', models.BooleanField(default=False)),
                ('valor_50porc', models.BooleanField(default=False)),
                ('num_parcela', models.BooleanField(default=False)),
                ('num_parcela_mais_1', models.BooleanField(default=False)),
                ('porcentagem', models.BooleanField(default=False)),
                ('porcentagem_mais_5', models.BooleanField(default=False)),
                ('padrao', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('nome',),
            },
        ),
    ]
