# Generated by Django 3.0.2 on 2020-01-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0002_remove_configuracaotexto_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaotexto',
            name='padrao',
            field=models.BooleanField(default=False),
        ),
    ]
