# Generated by Django 3.0.2 on 2020-01-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0004_auto_20200113_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaotexto',
            name='valor_da_entrada',
            field=models.BooleanField(default=False),
        ),
    ]
