# Generated by Django 3.0.2 on 2020-01-15 17:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0005_configuracaotexto_valor_da_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaotexto',
            name='criado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuracaotexto',
            name='modificado',
            field=models.DateField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
